config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/terms',      to: 'static_pages#terms'
  get  '/signup',     to: 'users#new'
  post  '/signup',    to: 'users#create'
  get    '/login',    to: 'sessions#new'
  post   '/login',    to: 'sessions#create'
  delete '/logout',   to: 'sessions#destroy'
  get 'auth/:provider/callback', to: 'sessions#create'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:show, :new, :create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :likes,               only: [:create, :destroy]
  resources :microposts do
    resources :comments,          only: [:create, :destroy]
  end
  resources :notifications,       only: :index
  resources :password_edits,      only: [:edit, :update]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page]).search(params[:search])
      @comment = Comment.new
      @comments = @micropost.comments
    end
    # app/views/リソース名/リソース名/アクション名.リソース名/アクション名.html.erb
    # app/views/static_pages/home.html.erb
  end
  
  def terms
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
<div class="center jumbotron">
  <h1>Welcome to the Instagram Clone</h1>
  <div class="top-page-space">
    <%= image_tag 'instagram.png', class: "top-page-logo" %>
  </div>
  <%= link_to "Sign up", signup_path, class: "btn btn-lg btn-primary" %>
  <%= link_to "Log in", login_path, class: "btn btn-lg btn-primary" %>
  <%= link_to "Facebook Log in", "/auth/facebook", class: "btn btn-lg btn-primary" %>
</div>


            
            
<% end %>

app/views/static_pages/terms.html.erb
<% provide(:title, "Terms of Use") %>

<h1>Terms of Use</h1>
<p>InstagramCloneへようこそ！</p>
<p>この利用規約は、InstagramCloneをご利用いただく際に適用されるものであり、InstagramCloneサービスに関する情報を提供するものです。InstagramCloneアカウントを作成する場合、またはInstagramCloneをご利用になる場合は、本規約に同意していただくことになります。</p>
<p>[料金]</p>
<p>本サービスの利用料は無料です。</p>
<p>[保証の否認及び免責事項]</p>
<p>本サービスに事実上または法律上の瑕疵（安全性，信頼性，正確性，完全性，有効性，特定の目的への適合性，セキュリティなどに関する欠陥，エラーやバグ，権利侵害などを含みます。）がないことを明示的にも黙示的にも保証しておりません。</p>
<p>本サービスに起因してユーザーに生じたあらゆる損害について一切の責任を負いません。</p>
  