config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/terms',      to: 'static_pages#terms'
  get  '/signup',     to: 'users#new'
  post  '/signup',    to: 'users#create'
  get    '/login',    to: 'sessions#new'
  post   '/login',    to: 'sessions#create'
  delete '/logout',   to: 'sessions#destroy'
  get 'auth/:provider/callback', to: 'sessions#create'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:show, :new, :create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :likes,               only: [:create, :destroy]
  resources :microposts do
    resources :comments,          only: [:create, :destroy]
  end
  resources :notifications,       only: :index
  resources :password_edits,      only: [:edit, :update]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <% if logged_in? %>
    <ul>
      <li><%= link_to "Photo post", new_micropost_path %></li>
    </ul>
    <% end %>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Instagram", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Notice", notifications_path %>
            <% if unchecked_notifications.any? %>
              <i class="fa fa-circle notification-circle"></i>
            <% end %>
          </li>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Photo post", new_micropost_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
          
          <!投稿が表示されるページは投稿検索---->
          <% if current_page?(users_path) || current_page?(notifications_path) %>
            <li>
              <%= form_tag(users_path,:method => 'get', class: "serach-window") do %>
                <%= text_field_tag :search, '', placeholder: 'user' %>
                <%= submit_tag 'Search', :name => nil %>
              <% end %>
            </li>
          <% elsif current_page?(root_path) || current_page?(new_micropost_path) %>
            <li>
              <%= form_tag(root_path,:method => 'get', class: "serach-window") do %>
                <%= text_field_tag :search, '', placeholder: 'comment' %>
                <%= submit_tag 'Search', :name => nil %>
              <% end %>
            </li>
          <% elsif current_page?(:controller => 'users', :action => 'show', :id => params[:id]) %>
            <li>
              <%= form_tag(user_path,:method => 'get', class: "serach-window") do %>
                <%= text_field_tag :search, '', placeholder: 'comment' %>
                <%= submit_tag 'Search', :name => nil %>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= form_tag(users_path,:method => 'get', class: "serach-window") do %>
                <%= text_field_tag :search, '', placeholder: 'user' %>
                <%= submit_tag 'Search', :name => nil %>
              <% end %>
            </li>
          <% end %>
          
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>